on click on sign:
	if line 3 of the block is "Solo Maze":
		teleport player to {waitloc}
		message "Generating random maze"
		wait 4 ticks
		execute console command "/cw -o -403 101 -4 -w minigameworld cs maze.js 155 10 10 4 2 ief"
		wait 1 second
		teleport the player to {location}


on click on sign:
	if line 3 of the block is "go to spawn":
		execute console command "/warp spawn %player%"
on click on sign:
	if line 3 of the block is "spawn":
		execute console command "/warp spawn %player%"

